Controllers/WeddingController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using WeddingPlanner.Models;

namespace WeddingPlanner.Controllers
{
    public class WeddingController : Controller
    {
        private int? UUID
        {
            get
            {
                return HttpContext.Session.GetInt32("UUID");
            }
        }

        private bool isLoggedIn
        {
            get
            {
                return UUID != null;
            }
        }
        private WeddingPlannerContext db;
        public WeddingController(WeddingPlannerContext context)
        {
            db = context;
        }

        [HttpGet("/dashboard")]
        public IActionResult Dashboard()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            List<Wedding> allWeddings = db.Weddings
                .Include(w => w.UserWeddingRSVP)
                    .ThenInclude(u => u.User)
                .ToList();
            // ViewBag.allWeddings = allWeddings;

            // bool existingRSVP = db.UserWeddingRSVPs
            //     .Include(u => u.Wedding)
            //     .Any(u => u.UserId == (int)UUID);
            // ViewBag.existingRSVP = existingRSVP;

            return View("Dashboard", allWeddings);
        }

        [HttpGet("/wedding/new")]
        public IActionResult NewWedding()
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            return View("NewWedding");
        }

        [HttpPost("/wedding/create")]
        public IActionResult CreateWedding(Wedding newWedding)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            if(ModelState.IsValid == false)
            {
                return View("NewWedding");
            }

            newWedding.CreatedBy = (int)UUID;
            db.Add(newWedding);
            db.SaveChanges();
            return RedirectToAction("Dashboard");
        }

        [HttpGet("/wedding/{weddingId}")]
        public IActionResult WeddingDetails(int weddingId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            Wedding queriedWedding = db.Weddings
                .Include(w => w.UserWeddingRSVP)
                    .ThenInclude(u => u.User)
                    // .ThenInclude(u => u.FirstName)
                .FirstOrDefault(w => w.WeddingId == weddingId);

            return View("WeddingDetails", queriedWedding);
        }

        [HttpPost("/wedding/rsvp")]
        public IActionResult WeddingRSVP(int weddingId, UserWeddingRSVP newRSVP)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }

            UserWeddingRSVP existingRSVP = db.UserWeddingRSVPs
                .FirstOrDefault(u => u.UserId == (int)UUID && u.WeddingId == weddingId);

            if(existingRSVP == null)
            {
                newRSVP.WeddingId = weddingId;
                newRSVP.UserId = (int)UUID;
                db.UserWeddingRSVPs.Add(newRSVP);
            }
            else
            {
                db.UserWeddingRSVPs.Remove(existingRSVP);
            }
    
            db.SaveChanges();
                return RedirectToAction("Dashboard");
        }

        [HttpPost("/wedding/delete")]
        public IActionResult DeleteWedding(int weddingId)
        {
            if(!isLoggedIn)
            {
                return RedirectToAction("Index", "Home");
            }
            Wedding deleteWedding = db.Weddings
                .SingleOrDefault(w => w.WeddingId == weddingId);
            db.Weddings.Remove(deleteWedding);
            db.SaveChanges();
            return RedirectToAction("Dashboard");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeddingPlanner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeddingPlanner</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wedding" asp-action="Dashboard">Dashboard</a>
                        </li>

                        @if(Context.Session.GetInt32("UUID") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Wedding" asp-action="NewWedding">New Wedding</a>
                            </li>
                            <li class="nav-item">
                                <form asp-controller="Home" asp-action="Logout">
                                <button class="btn btn-link">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WeddingPlanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>